on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: make test  

  release:
    runs-on: ubuntu-latest

    needs: runtests

    if: github.event_name == 'release'

    steps:
    - name: Get associated Github release
      if: github.event_name == 'release'
      id: get_release
      uses: bruceadams/get-release@v1.2.2

    - uses: actions/checkout@v2

    - name: Create dist
      run: make dist

    - name: Publish to Github Release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: xpmeter-${{ steps.get_release.outputs.tag_name }}.zip
        asset_name: xpmeter-${{ steps.get_release.outputs.tag_name }}.zip
        asset_content_type: application/zip
