on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  runtests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Lua
      run: |
        sudo apt update
        sudo apt install --no-install-recommends -y lua5.1

    - name: Run tests
      run: make test  

  release:
    runs-on: ubuntu-latest

    needs: runtests

    if: github.event_name == 'release'

    steps:
    - name: Get associated Github release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Create dist
      run: make dist

    - name: Publish to Github Release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: xpbuddy-${{ steps.get_release.outputs.tag_name }}.zip
        asset_name: xpbuddy-${{ steps.get_release.outputs.tag_name }}.zip
        asset_content_type: application/zip
